name: API Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: murine
          java-version: 24

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: murine
          java-version: 24

      - name: Run API Tests
        run: mvn clean test